apiVersion: v1
kind: Service
metadata:
  name: decos-pg-svc
  namespace: decos
  labels:
    app: decos-pg
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: decos-pg
  type: ClusterIP
